apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp
    type: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      type: backend
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        type: backend

    spec:
      containers:
      - name: my-backend-container
        image: rilok/random-digits
        ports:
        - containerPort: 4000