apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: NodePort
  selector:
    app: myapp-backend
    type: backend
  ports:
    - targetPort: 3000
      port: 80
      nodePort: 30009
